# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-20 23:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubToDoList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtask_name', models.CharField(max_length=250, unique=True)),
                ('status', models.BooleanField(default=True, verbose_name='Falta por hacer!')),
            ],
        ),
        migrations.CreateModel(
            name='ToDoList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=250, unique=True)),
                ('status', models.BooleanField(default=True, verbose_name='Falta por hacer!')),
            ],
            options={
                'ordering': ['task_name'],
            },
        ),
        migrations.AddField(
            model_name='subtodolist',
            name='todolist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todoapp.ToDoList'),
        ),
    ]
