# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-20 23:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_auto_20180220_2051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='subtodo_list',
        ),
        migrations.AddField(
            model_name='subtodolist',
            name='todolist',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='todoapp.ToDoList'),
            preserve_default=False,
        ),
    ]
