# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-21 00:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0004_auto_20180220_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtodolist',
            name='todolist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtodolist', to='todoapp.ToDoList'),
        ),
    ]
