# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-21 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0005_auto_20180220_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtodolist',
            name='status',
            field=models.BooleanField(choices=[(0, 'Falta por hacer!'), (1, 'Resuelta tarea!')], default=0),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='status',
            field=models.BooleanField(choices=[(0, 'Falta por hacer!'), (1, 'Resuelta tarea!')], default=0),
        ),
    ]
