# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-25 14:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0006_auto_20180221_0952'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SubToDoList',
            new_name='SubTodo',
        ),
        migrations.RenameModel(
            old_name='ToDoList',
            new_name='Todo',
        ),
    ]
